---
- name: "Perform pre tasks configurations (-u / -p for multiple bash possibilities)"
  register: output
  changed_when: output.rc != 0
  ignore_errors: true # Because of Docker limitations
  ansible.builtin.shell: |
    sysctl -w vm.max_map_count=524288
    sysctl -w fs.file-max=131072
    ulimit -n 131072
    ulimit -p 8192
    ulimit -u 8192

- name: "Create Docker network"
  community.docker.docker_network:
    name: "sonarqube_network"

- name: "Install PostgreSQL"
  community.docker.docker_container:
    name: "{{ install_sonarqube__postgresql_container_name }}"
    image: "postgres:latest"
    state: "started"
    recreate: false
    restart_policy: "always"
    hostname: "{{ install_sonarqube__postgresql_container_name }}"
    ports:
      - "127.0.0.1:5432:5432"
    env:
      POSTGRES_USER: "{{ install_sonarqube__postgres_sonarqube_login }}"
      POSTGRES_PASSWORD: "{{ install_sonarqube__postgres_sonarqube_password }}"
      POSTGRES_DB: "sonarqube"
    volumes:
      - "postgresql:/var/lib/postgresql"
      - "postgresql_data:/var/lib/postgresql/data"
    networks:
      - name: "sonarqube_network"

- name: "Install Sonarqube"
  community.docker.docker_container:
    name: "{{ install_sonarqube__container_name }}"
    image: "sonarqube:latest"
    state: "started"
    recreate: false
    restart_policy: "always"
    hostname: "{{ install_sonarqube__container_name }}"
    ports:
      - "{{ install_sonarqube__web_host }}:{{ install_sonarqube__web_port }}:9000"
    volumes:
      - "sonarqube_data:/opt/sonarqube/data"
      - "sonarqube_logs:/opt/sonarqube/logs"
      - "sonarqube_extensions:/opt/sonarqube/extensions"
    networks:
      - name: "sonarqube_network"
    env:
      SONAR_JDBC_URL: "jdbc:postgresql://{{ install_sonarqube__postgresql_container_name }}:5432/sonarqube"
      SONAR_JDBC_USERNAME: "{{ install_sonarqube__postgres_sonarqube_login }}"
      SONAR_JDBC_PASSWORD: "{{ install_sonarqube__postgres_sonarqube_password }}"
