---
- name: "Enable and start PostgreSQL"
  register: postgresql_service_status
  changed_when: not postgresql_service_status.state != "started"
  ansible.builtin.service:
    name: "postgresql"
    state: "started"
    daemon_reload: true
    enabled: yes

- name: "Enable and start SonarQube"
  register: sonarqube_service_status
  changed_when: not sonarqube_service_status.state != "started"
  ansible.builtin.service:
    name: "sonarqube"
    state: "started"
    daemon_reload: true
    enabled: yes

- name: "Restart SonarQube"
  register: sonarqube_service_status
  changed_when: not sonarqube_service_status.state != "started"
  ansible.builtin.service:
    name: "sonarqube"
    state: "restarted"
    daemon_reload: true
    enabled: yes