---
- name: "Converge"
  hosts: "all"
  tasks:
    # replace these tasks with whatever you find suitable to test
    - name: "Copy something to test use of synchronize module"
      ansible.builtin.copy:
        src: "/etc/hosts"
        dest: "/tmp/hosts-from-controller"
        mode: 0700

    - name: "Include labocbz.install_sonarqube"
      tags:
        - "labocbz.install_sonarqube"
      vars:
        install_sonarqube_user: "{{ inv_install_sonarqube_user }}"
        install_sonarqube_group: "{{ inv_install_sonarqube_group }}"
        install_sonarqube_postgres_user: "{{ inv_install_sonarqube_postgres_user }}"
        install_sonarqube_postgres_group: "{{ inv_install_sonarqube_postgres_group }}"
        install_sonarqube_postgres_sonarqube_login: "{{ inv_install_sonarqube_postgres_sonarqube_login }}"
        install_sonarqube_postgres_sonarqube_password: "{{ inv_install_sonarqube_postgres_sonarqube_password }}"
        install_sonarqube_lib_path: "{{ inv_install_sonarqube_lib_path }}"
        install_sonarqube_log_path: "{{ inv_install_sonarqube_log_path }}"
        install_sonarqube_version: "{{ inv_install_sonarqube_version }}"
        install_sonarqube_web_heap: "{{ inv_install_sonarqube_web_heap }}"
        install_sonarqube_web_host: "{{ inv_install_sonarqube_web_host }}"
        install_sonarqube_web_context: "{{ inv_install_sonarqube_web_context }}"
        install_sonarqube_web_port: "{{ inv_install_sonarqube_web_port }}"
        install_sonarqube_elasticsearch_heap: "{{ inv_install_sonarqube_elasticsearch_heap }}"
        install_sonarqube_log_level: "{{ inv_install_sonarqube_log_level }}"
        install_sonarqube_log_retention: "{{ inv_install_sonarqube_log_retention }}"
        install_sonarqube_elasticsearch_port: "{{ inv_install_sonarqube_elasticsearch_port }}"
      ansible.builtin.include_role:
        name: "labocbz.install_sonarqube"
