---
# if you have any prepararion task
- name: "Prepare"
  hosts: "local"
  gather_facts: true
  tasks:

    #- name: "Include cryptographic content var file"
    #  ansible.builtin.include_vars: "../../tests/certs/main.yml"

    #- name: "Include labocbz.prepare_host"
    #  tags:
    #    - "labocbz.prepare_host"
    #  vars:
    #    prepare_host__system_users: "{{ inv_prepare_host__system_users }}"
    #  ansible.builtin.include_role:
    #    name: "labocbz.prepare_host"

    - name: "Gather facts from all hosts"
      delegate_to: "{{ item }}"
      delegate_facts: true
      loop: "{{ groups['local'] }}"
      ansible.builtin.setup:

    - name: "Edit /etc/hosts file to add all hosts"
      loop: "{{ groups['local'] }}"
      loop_control:
        loop_var: host
      register: output
      changed_when: output.rc != 0
      ansible.builtin.shell: "echo \"{{ hostvars[host]['ansible_default_ipv4']['address'] }}  {{ host }} # from Molecule\" >> /etc/hosts"

    - name: "Include labocbz.install_docker"
      tags:
        - "labocbz.install_docker"
      vars:
        install_docker__portainer: "{{ inv_install_docker__portainer }}"
        install_docker__portainer_http_port: "{{ inv_install_docker__portainer_http_port }}"
        install_docker__portainer_https_port: "{{ inv_install_docker__portainer_https_port }}"
        install_docker__portainer_agent_port: "{{ inv_install_docker__portainer_agent_port }}"
        install_docker__portainer_container_name: "{{ inv_install_docker__portainer_container_name }}"
        install_docker__portainer_volume_name: "{{ inv_install_docker__portainer_volume_name }}"
        install_docker__portainer_ssl: "{{ inv_install_docker__portainer_ssl }}"
        install_docker__portainer_ssl_volume_name: "{{ inv_install_docker__portainer_ssl_volume_name }}"
        install_docker__portainer_ssl_key: "{{ inv_install_docker__portainer_ssl_cert }}"
        install_docker__watchtower: "{{ inv_install_docker__watchtower }}"
        install_docker__watchtower_poll_interval: "{{ inv_install_docker__watchtower_poll_interval }}"
        install_docker__watchtower_cleanup: "{{ inv_install_docker__watchtower_cleanup }}"
        install_docker__watchtower_include_restarting: "{{ inv_install_docker__watchtower_include_restarting }}"
        install_docker__watchtower_include_stopped: "{{ inv_install_docker__watchtower_include_stopped }}"
        install_docker__watchtower_no_restart: "{{ inv_install_docker__watchtower_no_restart }}"
        install_docker__portainer_address: "{{ inv_install_docker__portainer_address }}"
        install_docker__handle_clean: "{{ inv_install_docker__handle_clean }}"
        install_docker__clean_cron_file: "{{ inv_install_docker__clean_cron_file }}"
        install_docker__clean_weekday: "{{ inv_install_docker__clean_weekday }}"
        install_docker__clean_minute: "{{ inv_install_docker__clean_minute }}"
        install_docker__clean_hour: "{{ inv_install_docker__clean_hour }}"
        install_docker__disable_swap: "{{ inv_install_docker__disable_swap }}"
      ansible.builtin.include_role:
        name: "labocbz.install_docker"
