---
- name: "Converge"
  hosts: "cicd-docker-dind"
  tasks:

    - name: "Include labocbz.install_sonarqube"
      tags:
        - "labocbz.install_sonarqube"
      vars:
        install_sonarqube__postgres_sonarqube_login: "{{ inv_install_sonarqube__postgres_sonarqube_login }}"
        install_sonarqube__postgres_sonarqube_password: "{{ inv_install_sonarqube__postgres_sonarqube_password }}"
        install_sonarqube__container_name: "{{ inv_install_sonarqube__container_name }}"
        install_sonarqube__postgresql_container_name: "{{ inv_install_sonarqube__postgresql_container_name }}"
        install_sonarqube__web_host: "{{ inv_install_sonarqube__web_host }}"
        install_sonarqube__web_port: "{{ inv_install_sonarqube__web_port }}"
      ansible.builtin.include_role:
        name: "labocbz.install_sonarqube"
