---
# Don't forget to keep this file updated
# molecule/<scenario>/verify.yml
- name: "Verify"
  hosts: "cicd-docker-dind"
  gather_facts: false
  tasks:

    - name: "Check docker-compose command response"
      register: output
      changed_when: output.rc != 0
      failed_when: output.rc != 0
      ansible.builtin.command: "docker -v"

    - name: "Check docker-compose command response"
      register: output
      changed_when: output.rc != 0
      failed_when: output.rc != 0
      ansible.builtin.command: "docker-compose -v"

    #- name: "Check Soanrqube HTTP URL"
    #  register: result
    #  failed_when: result.status != 200
    #  ansible.builtin.uri:
    #    url: "http://{{ inventory_hostname }}:{{ inv_install_sonarqube__web_port }}/"
    #    method: "GET"
